language: python

python:
    - 2.7

install: "pip install -r requirements.txt"

script: flake8 tests healthmonger; nosetests tests;python healthmonger/healthmonger.py >> logs/healthmonger.log 2>> logs/errors.log &; behave integration/features/healthmonger.feature